### PR TITLE
chore: imessageclone maintenance, upgrading dependencies, added alert if no env variables found

### PR DESCRIPTION
**Pull request by khushal87**

### CODE REVIEW

**Comment by vanGalilea** [comment]
A crash occurs when trying to take a photo and post it on an iOS device

**Comment by vanGalilea** [comment]
1. Keyboard covers messageinput
File (1)

2. You can not create a new channel with and send messages, see "you can not send message in this chat..." error message below
File (2)

3.keyboard over messageinput again
File

**Review by vanGalilea — CHANGES_REQUESTED** [review]
I've attached some screenshots of styling issues, a limitation when creating a chat and crash on ios when taking a photo

**Comment by khushal87** [comment]
image

Not able to reproduce 1 and 3 on my iPhone 13 @vanGalilea

**Comment by khushal87** [comment]
Fixed 2 @vanGalilea and

> A crash occurs when trying to take a photo and post it on an iOS device

Fixed

**Review by vanGalilea — APPROVED** [review]

**Pull request merged**
